import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import styles from "./layout.module.scss";
import { Layout, Menu } from "antd";
import { Header, Footer } from "antd/es/layout/layout";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const items = [
	{ key: 0, label: <Link href={`/`}>Home</Link> },
	{ key: 1, label: <Link href={`/posts`}>Posts</Link> },
  { key: 2, label: <Link href={`/album`}>Album</Link> },
  { key: 3, label: <Link href={`/todo`}>Todo</Link> },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AntdRegistry>
					<Layout className={styles.root}>
						<Header className={styles.header}>
							<Menu
								theme="dark"
								mode="horizontal"
								defaultSelectedKeys={["0"]}
								items={items}
								style={{ flex: 1, minWidth: 0 }}
							/>
						</Header>
						<div className={styles.main}>{children}</div>
						<Footer className={styles.footer}>Footer</Footer>
					</Layout>
				</AntdRegistry>
			</body>
		</html>
	);
}
